#!/bin/sh
## Adapt according to you build environment.
VERSION=20
DISTRO=nodistro
PACKAGE=nodejs

set -e

apt update
KEY_URL="https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
APT_URL="https://deb.nodesource.com/node_${VERSION}.x ${DISTRO} main"

curl -fsSL ${KEY_URL} | gpg -o /etc/apt/trusted.gpg.d/${PACKAGE}.gpg --dearmor
echo "deb [signed-by=/etc/apt/trusted.gpg.d/${PACKAGE}.gpg] ${APT_URL}" > /etc/apt/sources.list.d/${PACKAGE}.list
apt update
