#!/bin/sh
## Adapt according to you build environment.
VERSION=node_18.x
DISTRO=focal

set -e

apt update
apt -y install wget apt-transport-https gnupg ca-certificates
wget --quiet -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

echo "deb https://deb.nodesource.com/$VERSION $DISTRO main" | tee /etc/apt/sources.list.d/nodesource.list
echo "deb-src https://deb.nodesource.com/$VERSION $DISTRO main" | tee -a /etc/apt/sources.list.d/nodesource.list
apt update